// Generated by kea-typegen on Sat, 23 Oct 2021 21:33:15 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

export interface appLogicType extends Logic {
  actionCreators: {
    goFaster: () => {
      type: 'go faster (src.appLogic)'
      payload: {
        value: boolean
      }
    }
  }
  actionKeys: {
    'go faster (src.appLogic)': 'goFaster'
  }
  actionTypes: {
    goFaster: 'go faster (src.appLogic)'
  }
  actions: {
    goFaster: () => void
  }
  constants: {}
  defaults: {
    speed: number
  }
  events: {}
  key: undefined
  listeners: {}
  path: ['src', 'appLogic']
  pathString: 'src.appLogic'
  props: Record<string, unknown>
  reducer: (
    state: any,
    action: () => any,
    fullState: any
  ) => {
    speed: number
  }
  reducerOptions: {}
  reducers: {
    speed: (state: number, action: any, fullState: any) => number
  }
  selector: (state: any) => {
    speed: number
  }
  selectors: {
    speed: (state: any, props?: any) => number
  }
  sharedListeners: {}
  values: {
    speed: number
  }
  _isKea: true
  _isKeaWithKey: false
}
